### ISSUE TITLE
Erorr wal

### ISSUE THREAD

**Issue by buikhanh0411** [niksingh710/nvim#1]
I get erorr while open nvim

```
lazy.nvim: Failed to run config for pywal16.nvim

vim/_editor.lua:0: /home/khanh/.config/nvim/init.lua..nvim_exec2() called at /home/khanh/.config/nvim/init.lua:0: Vim(source):E484: Can't open file /home/khanh/.cache/wal/colors-wal.vim'

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - /pywal16.nvim/lua/pywal16/core.lua:4 _in_ **get_colors**
  - /pywal16.nvim/lua/pywal16/init.lua:6 _in_ `**setup**`
  - `.config/nvim/init.lua:86``
  
```
  
  
  what this erorr?

**Comment by semi710** [comment]
I use a tool named `pywal` that extracts colors from my wallpaper and set's it to my whole system.
this error is because you don't have that tool.
to fix it just remove the file `lua/plugins/colorschemes/pywal16.lua`

have removed in the current master too.
