### ISSUE TITLE
Add some plugin

### ISSUE THREAD

**Issue by buikhanh0411** [niksingh710/nvim#2]
How to add plugin(coc)?
Im a newbie

**Comment by semi710** [comment]
> How to add plugin(coc)? Im a newbie

https://github.com/nvim-lua/kickstart.nvim

Check this out, this will give you a working understanding of nvim. And it's config.

Also, there are many plugin managers for nvim, so it is different for every plugin.

In my configuration, I just create a file in plugins Dir and return the plugin configuration in Lua.

**Comment by buikhanh0411** [comment]
> > How to add plugin(coc)? Im a newbie
> 
> https://github.com/nvim-lua/kickstart.nvim
> 
> Check this out, this will give you a working understanding of nvim. And it's config.
> 
> Also, there are many plugin managers for nvim, so it is different for every plugin.
> 
> In my configuration, I just create a file in plugins Dir and return the plugin configuration in Lua.

thanks a lot ❤️❤️❤️
